package com.android.aschat.feature_host.domain.model.hostdetail.userinfo


data class HostInfo(
    val about: String,
    val acceptMultipleCall: Boolean,
    val age: Int,
    val auditStatus: Int,
    val avatar: String,
    val avatarMiddleThumbUrl: String,
    val avatarThumbUrl: String,
    val avatarUrl: String,
    val birthday: String,
    val country: String,
    val followNum: Int,
    val gender: Int,
    val grade: Int,
    val isAnswer: Boolean,
    val isBlock: Boolean,
    val isClub: Boolean,
    val isHavePassword: Boolean,
    val isInternal: Boolean,
    val isProbationPeriod: Boolean,
    val isRecharge: Boolean,
    val isSwitchNotDisturbCall: Boolean,
    val isSwitchNotDisturbIm: Boolean,
    val isVip: Boolean,
    val language: String,
    val level: Int,
    val mediaList: List<Media>,
    val nickname: String,
    val praiseNum: Int,
    val rongcloudToken: String,
    val tagDetails: List<Any>,
    val tagsList: List<Any>,
    val unitPrice: Int,
    val userId: String,
    val userType: Int,
    val vipUnitPrice: Int
)